# Python Assignment: Variables, Operators, and Type Casting
### Name: ANAND SHIVAM | Date: 01/09/2024

**1. Understanding Variables**

a. Define a variable in Python. Provide an example of how to create a variable that
stores your name.

b. What is the difference between a variable and a constant? Can we have constants in
Python?

-  Variables in python is a temporary container which stores the value assigned to it using "=" operator

In [ ]:
#We can create a variable to store name as shown below:

myname = 'Anand Shivam'
print(myname)
print(type(myname))

Anand Shivam
<class 'str'>

-  Key Difference between Variables and constants is that value of variables can changed in the
code while constants values are fixed and should not change at all.
-  Variables are used for data that changes like user input or calculation results but constants are suitable for values that remain constant throughout e.g value of Ï€ , Gravity, Speed of Light

-  we dont have built in constants in python , but it can be achieved by following some best practices like naming the variable in upper case or having a separate class for the constants.

**2. Working with Different Data Types**

a. Create variables of the following types in Python:
1. Integer
2. Float
3. String
4. Boolean

b. Write a Python script to display the type of each variable you created.

In [ ]:
#creating variable for different data types

num = 23 #Integer
float_num = 12.5 #float
str = 'AnalyticsWithAnand' #string
bol = True #boolean

#printing data type of each variable
print (type(num))
print (type(float_num))
print (type(str))
print (type(bol))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>

**3. Arithmetic Operators**

a. Explain the following arithmetic operators with examples:
1. Addition (`+`)
2. Subtraction (`-`)
3. Multiplication (``)
4. Division (`/`)
5. Floor Division (`//`)
6. Modulus (`%`)
7. Exponentiation (``)

**Addition(+)**: Adds two values , This operator is used for numbers to do arithmetic addition or for strings to concatenate them

In [1]:
#For numbers
a = 2
b = 5
result = a + b
print(result)

7

In [ ]:
#For Strings
str1 = 'Analytics'
str2 = 'With'
str3 = 'Anand'
output = str1 + str2 +str3
print(output)

AnalyticsWithAnand

**Subtraction(-)**: Subtracts second value from first one , This operator is used for numbers to do arithmetic subtraction

In [ ]:
a = 111
b = 52
result = a - b
print(result)

59

**Multiplication(*)**: Multiplies two or more numbers and also repeat the sequence like lists and strings

In [4]:
# Multiplying numbers
a = 6
b = 5
result = a * b
print(result)

# Repeating a string
str1 = "Hello"
result = str1 * 3
print(result)

# Repeating a list
list_1 = [0,1, 2]
result = list_1 * 3
print(result)

30
HelloHelloHello
[0, 1, 2, 0, 1, 2, 0, 1, 2]

**Division(/)**: The division operator (/) divides one number by another and returns quotient as a floating-point result.

In [1]:
a = 7
b = 2
result = a / b
print(result)

3.5

**Foor Division(//)**: The division operator (//) divides one number by another and returns quotient as result which is rounded of to nearest integer value.

In [3]:
a = 7
b = 2
result = a // b
print(result)
print (type(result))

3
<class 'int'>

**Modulus (%)** The modulus operator (%) returns the remainder of the division of one number by another.

In [5]:
a = 7
b = 2
result = a % b
print(result)

1

 **Exponentiation ('**') ** The exponentiation operator (**) raises one number to the power of another.

In [6]:
a = 7
b = 2
result = a ** b
print(result)

49

b. Write a Python script to calculate the area of a rectangle using variables `length`
and `width` with values 5 and 10, respectively. Use the multiplication operator.

In [7]:
length = 5
width = 10
area = length * width
print("Area of rectangle:", area)

Area of rectangle: 50

**4. Comparison and Logical Operators**

a. Explain the following comparison operators with examples:
1. Equal to (`==`)
2. Not equal to (`!=`)
3. Greater than (`>`)
4. Less than (`<`)
5. Greater than or equal to (`>=`)
6. Less than or equal to (`<=`)

**Equal to (==)**
The equal to operator (==) checks if two values are equal. It returns True if they are equal and False otherwise.

In [8]:
a = 1
b = 1
result = a == b
print(result)

c = 52
d = 35
result = c == d
print(result)

True
False

**Not equal to (!=)**
The not equal to operator (!=) checks if two values are not equal. It returns True if they are not equal and False otherwise.

In [10]:
a = 1
b = 1
result = a != b
print(result)

c = 52
d = 35
result = c != d
print(result)

False
True

**Greater than (>)**
The greater than operator (>) checks if one value is greater than another. It returns True if the first value is greater and False otherwise

In [11]:
a = 1
b = 1
result = a > b
print(result)

c = 52
d = 35
result = c > d
print(result)

False
True

**Less than (<)**
The less than operator (<) checks if one value is less than another. It returns True if the first value is less and False otherwise.

In [13]:
a = 1
b = 1
result = a < b
print(result)

c = 25
d = 35
result = c < d
print(result)

False
True

**Greater than or equal to (>=)**
The greater than or equal to operator (>=) checks if one value is greater than or equal to another. It returns True if the first value is greater than or equal to the second value and False otherwise

In [15]:
a = 1
b = 1
result = a >= b
print(result)

c = 25
d = 35
result = c >= d
print(result)

True
False

**Less than or equal to (<=)**
The less than or equal to operator (<=) checks if one value is less than or equal to another. It returns True if the first value is less than or equal to the second value and False otherwise.

In [16]:
a = 1
b = 1
result = a <= b
print(result)

c = 25
d = 35
result = c <= d
print(result)

True
True

b. Using logical operators (`and`, `or`, `not`), write a Python script that checks if a
number is positive and even.

In [17]:
num = int(input("Enter the number : "))
if num > 0:
          if num%2 == 0:
            print("Positive and even")
          else:
            print("Positive and odd")
elif num == 0:
    print("Number is Zero")
else :
    print ("Negative number")

Enter the number : 25
Positive and odd

**5. Type Casting in Python**

a. What is type casting? Explain the difference between implicit and explicit type
casting with examples.

Type casting is the process of converting a value from one data type to another.

Major difference between implicit and explicit type casting is as below :

* Implicit Type Casting:

Automatically performed by Python.

Occurs when mixing different data types in operations.

Example: Adding an integer to a float results in a float.
* Explicit Type Casting:

Manually performed by the programmer.

Uses functions like int(), float(), str(), etc.

Example: Converting a float to an integer or an integer to a string.

In [18]:
# Implicit type casting
a = 5
b = 2.5
result = a + b
print(result)
print(type(result))

7.5
<class 'float'>

In [19]:
# Explicit type casting
a = 5.6
b = int(a)
print(b)
print(type(b))

c = 10
d = str(c)
print(d)
print(type(d))

5
<class 'int'>
10
<class 'str'>

b. Write a Python script that:
1. Converts a float to an integer.
2. Converts an integer to a string.
3. Converts a string to a float

In [21]:
#1. Converts a float to an integer
a = 5.35
b = int(a)
print(b)
print(type(b))

#2. Converts an integer to a string.
c = 10
d = str(c)
print(d)
print(type(d))

#Converts a string to a float
e = '2.5'
f = float(e)
print(f)
print(type(f))

5
<class 'int'>
10
<class 'str'>
2.5
<class 'float'>

**6. Practical Exercise: Mini Calculator**

Write a Python script that asks the user to input two numbers and then:
1. Adds the two numbers and prints the result.
2. Subtracts the second number from the first and prints the result.
3. Multiplies the two numbers and prints the result.
4. Divides the first number by the second and prints the result (handle division by zero).
5. Converts the sum of the numbers to a string and prints the type of the result

In [23]:
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

# Addition
sum_result = num1 + num2
print("Sum:", sum_result)

# Subtraction
sub_result = num1 - num2
print("Subtraction:", sub_result)

# Multiplication
mul_result = num1 * num2
print("Multiplication:", mul_result)

# Division
if num2 != 0:
    div_result = num1 / num2
    print("Division:", div_result)
else:
    print("Division by zero is not allowed.")

# Convert the sum to a string and print the type
sum_str = str(sum_result)
print("Type of Sum:", type(sum_str))

Enter the first number: 48
Enter the second number: 12
Sum: 60.0
Subtraction: 36.0
Multiplication: 576.0
Division: 4.0
Type of Sum: <class 'str'>